#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
#
# Source0 file verified with key 0xA2C794A986419D8A (tstellar@redhat.com)
#
%define keepstatic 1
Name     : llvm15
Version  : 15.0.7
Release  : 166
URL      : https://github.com/llvm/llvm-project/releases/download/llvmorg-15.0.7/llvm-project-15.0.7.src.tar.xz
Source0  : https://github.com/llvm/llvm-project/releases/download/llvmorg-15.0.7/llvm-project-15.0.7.src.tar.xz
Source1  : https://github.com/llvm/llvm-project/releases/download/llvmorg-15.0.7/llvm-project-15.0.7.src.tar.xz.sig
Summary  : Google microbenchmark framework
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause ISC MIT MPL-2.0 NCSA
Requires: llvm15-bin = %{version}-%{release}
Requires: llvm15-lib = %{version}-%{release}
Requires: llvm15-license = %{version}-%{release}
BuildRequires : Sphinx
BuildRequires : Vulkan-Headers-dev Vulkan-Loader-dev Vulkan-Tools
BuildRequires : Z3-dev
BuildRequires : Z3-dev32
BuildRequires : binutils-dev
BuildRequires : buildreq-cmake
BuildRequires : cmake
BuildRequires : curl-dev
BuildRequires : doxygen
BuildRequires : elfutils-dev
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : git
BuildRequires : glibc-dev
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : googletest-dev
BuildRequires : libffi-dev
BuildRequires : libffi-dev32
BuildRequires : libstdc++-dev
BuildRequires : libxml2-dev
BuildRequires : libxml2-dev32
BuildRequires : llvm
BuildRequires : llvm-dev
BuildRequires : lua-dev
BuildRequires : ncurses-dev
BuildRequires : ninja
BuildRequires : perl
BuildRequires : pkg-config
BuildRequires : pkgconfig(32libffi)
BuildRequires : pkgconfig(libedit)
BuildRequires : pkgconfig(libffi)
BuildRequires : protobuf-dev
BuildRequires : pypi(pybind11)
BuildRequires : python3-dev
BuildRequires : rsync
BuildRequires : swig
BuildRequires : valgrind-dev
BuildRequires : zlib-dev
BuildRequires : zlib-dev32
Patch1: llvm-0001-Improve-physical-core-count-detection.patch
Patch2: llvm-0002-Produce-a-normally-versioned-libLLVM.patch
Patch3: llvm-0003-Allow-one-more-FMA-fusion.patch
Patch4: clang-0001-Detect-Clear-Linux-and-apply-Clear-s-default-linker-.patch
Patch5: clang-0002-Make-Clang-default-to-Westmere-on-Clear-Linux.patch
Patch6: clang-0003-Add-the-LLVM-major-version-number-to-the-Gold-LTO-pl.patch
Patch7: clang-0004-Add-a-couple-more-f-instructions-that-GCC-has-that-C.patch
Patch8: clang-0005-Don-t-error-on-ftrivial-auto-var-init-zero.patch
Patch9: compiler-rt-0001-Reduce-mixing-and-matching-sys-and-linux.patch
Patch10: compiler-rt-0002-Add-missing-header-for-linux.patch

%description
Polly - Polyhedral optimizations for LLVM
-----------------------------------------
http://polly.llvm.org/

%package bin
Summary: bin components for the llvm15 package.
Group: Binaries
Requires: llvm15-license = %{version}-%{release}

%description bin
bin components for the llvm15 package.


%package dev
Summary: dev components for the llvm15 package.
Group: Development
Requires: llvm15-lib = %{version}-%{release}
Requires: llvm15-bin = %{version}-%{release}
Provides: llvm15-devel = %{version}-%{release}
Requires: llvm15 = %{version}-%{release}

%description dev
dev components for the llvm15 package.


%package extras-libclang
Summary: extras-libclang components for the llvm15 package.
Group: Default

%description extras-libclang
extras-libclang components for the llvm15 package.


%package extras-libclang-cpp
Summary: extras-libclang-cpp components for the llvm15 package.
Group: Default

%description extras-libclang-cpp
extras-libclang-cpp components for the llvm15 package.


%package extras-libllvm
Summary: extras-libllvm components for the llvm15 package.
Group: Default

%description extras-libllvm
extras-libllvm components for the llvm15 package.


%package lib
Summary: lib components for the llvm15 package.
Group: Libraries
Requires: llvm15-license = %{version}-%{release}

%description lib
lib components for the llvm15 package.


%package license
Summary: license components for the llvm15 package.
Group: Default

%description license
license components for the llvm15 package.


%prep
%setup -q -n llvm-project-15.0.7.src
cd %{_builddir}/llvm-project-15.0.7.src
%patch -P 1 -p1
%patch -P 2 -p1
%patch -P 3 -p1
%patch -P 4 -p1
%patch -P 5 -p1
%patch -P 6 -p1
%patch -P 7 -p1
%patch -P 8 -p1
%patch -P 9 -p1
%patch -P 10 -p1

%build
## build_prepend_once content
# Bootstrap Clang and the table generators
# See https://build.opensuse.org/package/view_file/devel:tools:compiler/llvm10/llvm10.spec?expand=1
pushd llvm
mkdir clr-bootstrap-build
pushd clr-bootstrap-build
CFLAGS="`sed -E 's/-Wl,\S+\s//g; s/-Wp,-D_FORTIFY_SOURCE=2//; s/-feliminate-unused-debug-types//' <<<$CFLAGS` -fno-integrated-as"
CXXFLAGS="`sed -E 's/-Wl,\S+\s//g; s/-Wp,-D_FORTIFY_SOURCE=2//; s/-feliminate-unused-debug-types//' <<<$CXXFLAGS` -fno-integrated-as"
%cmake .. \
-G Ninja \
-DCMAKE_BUILD_TYPE=Release \
-DBUILD_SHARED_LIBS:BOOL=OFF \
-DCMAKE_C_COMPILER=clang \
-DCMAKE_C_FLAGS="$CFLAGS -g0" \
-DCMAKE_CXX_COMPILER=clang++ \
-DCMAKE_CXX_FLAGS="$CXXFLAGS -g0" \
-DLLVM_ENABLE_PROJECTS="clang" \
-DLLVM_BUILD_LLVM_DYLIB:BOOL=OFF \
-DLLVM_LINK_LLVM_DYLIB:BOOL=OFF \
-DLLVM_ENABLE_ASSERTIONS=OFF \
-DLLVM_TARGETS_TO_BUILD=Native \
-DCLANG_ENABLE_ARCMT:BOOL=OFF \
-DCLANG_ENABLE_STATIC_ANALYZER:BOOL=OFF \
-DCMAKE_SKIP_RPATH:BOOL=OFF \
-DLLVM_LIBDIR_SUFFIX=64 \
-DLLVM_BINUTILS_INCDIR=/usr/include \
-DLLVM_HOST_TRIPLE="x86_64-generic-linux" \
-DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3
ninja -v
popd
export PATH=/usr/lib64/ccache/bin/:${PWD}/clr-bootstrap-build/bin:${PATH}
export LLVM_AR=${PWD}/clr-bootstrap-build/bin/llvm-ar
export LLVM_RANLIB=${PWD}/clr-bootstrap-build/bin/llvm-ranlib
export LLVM_TABLEGEN=${PWD}/clr-bootstrap-build/bin/llvm-tblgen
export CLANG_TABLEGEN=${PWD}/clr-bootstrap-build/bin/clang-tblgen
popd
## build_prepend_once end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1689819078
unset LD_AS_NEEDED
pushd llvm
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export CC=clang
export CXX=clang++
export LD=ld.gold
CFLAGS=${CFLAGS/ -Wa,/ -fno-integrated-as -Wa,}
CXXFLAGS=${CXXFLAGS/ -Wa,/ -fno-integrated-as -Wa,}
export CFLAGS="-O2 -g -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=32 -Wformat -Wformat-security -Wno-error -Wl,-z,max-page-size=0x4000 -march=westmere"
export CXXFLAGS=$CFLAGS
export FFLAGS="-O2 -g -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=32 -Wno-error -Wl,-z,max-page-size=0x4000 -march=westmere"
export FCFLAGS=$FFLAGS
unset LDFLAGS
unset LDFLAGS
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%cmake .. -G Ninja \
-DCMAKE_C_FLAGS="`sed -E 's/-Wl,\S+\s//g; s/-Wp,-D_FORTIFY_SOURCE=2//' <<<$CFLAGS`" \
-DCMAKE_CXX_FLAGS="`sed -E 's/-Wl,\S+\s//g; s/-Wp,-D_FORTIFY_SOURCE=2//' <<<$CXXFLAGS`" \
-DCMAKE_EXE_LINKER_FLAGS="$CXXFLAGS -Wl,--as-needed -Wl,--build-id=sha1" \
-DCMAKE_MODULE_LINKER_FLAGS="$CXXFLAGS -Wl,--as-needed -Wl,--build-id=sha1" \
-DCMAKE_SHARED_LINKER_FLAGS="$CXXFLAGS -Wl,--as-needed -Wl,--build-id=sha1" \
-DENABLE_LINKER_BUILD_ID=ON \
-DCLANG_DEFAULT_PIE_ON_LINUX=ON \
-DBUILD_SHARED_LIBS:BOOL=OFF \
-DLLVM_LINK_LLVM_DYLIB:BOOL=ON \
-DCLANG_LINK_CLANG_DYLIB:BOOL=ON \
-DLLVM_BUILD_RUNTIME:BOOL=ON \
-DLLVM_BUILD_TOOLS:BOOL=ON \
-DLLVM_ENABLE_FFI:BOOL=ON -DFFI_INCLUDE_DIR=`pkg-config --variable=includedir libffi` \
-DLLVM_ENABLE_RTTI:BOOL=ON \
-DLLVM_ENABLE_ZLIB:BOOL=ON \
-DLLVM_REQUIRES_RTTI:BOOL=ON \
-DLLVM_TABLEGEN=$LLVM_TABLEGEN \
-DCLANG_TABLEGEN=$CLANG_TABLEGEN \
-DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra;" \
-DLLVM_LIBDIR_SUFFIX=64 \
-DLLVM_BINUTILS_INCDIR=/usr/include \
-DLLVM_HOST_TRIPLE="x86_64-generic-linux" \
-DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3
ninja  %{?_smp_mflags}
popd
mkdir -p clr-build32
pushd clr-build32
export GCC_IGNORE_WERROR=1
export CC=clang
export CXX=clang++
export LD=ld.gold
CFLAGS=${CFLAGS/ -Wa,/ -fno-integrated-as -Wa,}
CXXFLAGS=${CXXFLAGS/ -Wa,/ -fno-integrated-as -Wa,}
export CFLAGS="-O2 -g -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=32 -Wformat -Wformat-security -Wno-error -Wl,-z,max-page-size=0x4000 -march=westmere"
export CXXFLAGS=$CFLAGS
export FFLAGS="-O2 -g -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=32 -Wno-error -Wl,-z,max-page-size=0x4000 -march=westmere"
export FCFLAGS=$FFLAGS
unset LDFLAGS
unset LDFLAGS
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig:/usr/share/pkgconfig"
export ASFLAGS="${ASFLAGS}${ASFLAGS:+ }--32"
export CFLAGS="${CFLAGS}${CFLAGS:+ }-m32 -mstackrealign"
export CXXFLAGS="${CXXFLAGS}${CXXFLAGS:+ }-m32 -mstackrealign"
export LDFLAGS="${LDFLAGS}${LDFLAGS:+ }-m32 -mstackrealign"
%cmake -DLIB_INSTALL_DIR:PATH=/usr/lib32 -DCMAKE_INSTALL_LIBDIR=/usr/lib32 -DLIB_SUFFIX=32 .. -G Ninja \
-DCMAKE_C_FLAGS="`sed -E 's/-Wl,\S+\s//g; s/-Wp,-D_FORTIFY_SOURCE=2//' <<<$CFLAGS`" \
-DCMAKE_CXX_FLAGS="`sed -E 's/-Wl,\S+\s//g; s/-Wp,-D_FORTIFY_SOURCE=2//' <<<$CXXFLAGS`" \
-DCMAKE_EXE_LINKER_FLAGS="$CXXFLAGS -Wl,--as-needed -Wl,--build-id=sha1" \
-DCMAKE_MODULE_LINKER_FLAGS="$CXXFLAGS -Wl,--as-needed -Wl,--build-id=sha1" \
-DCMAKE_SHARED_LINKER_FLAGS="$CXXFLAGS -Wl,--as-needed -Wl,--build-id=sha1" \
-DENABLE_LINKER_BUILD_ID=ON \
-DCLANG_DEFAULT_PIE_ON_LINUX=ON \
-DBUILD_SHARED_LIBS:BOOL=OFF \
-DLLVM_LINK_LLVM_DYLIB:BOOL=ON \
-DCLANG_LINK_CLANG_DYLIB:BOOL=ON \
-DLLVM_BUILD_RUNTIME:BOOL=ON \
-DLLVM_BUILD_TOOLS:BOOL=ON \
-DLLVM_ENABLE_FFI:BOOL=ON -DFFI_INCLUDE_DIR=`pkg-config --variable=includedir libffi` \
-DLLVM_ENABLE_RTTI:BOOL=ON \
-DLLVM_ENABLE_ZLIB:BOOL=ON \
-DLLVM_REQUIRES_RTTI:BOOL=ON \
-DLLVM_TABLEGEN=$LLVM_TABLEGEN \
-DCLANG_TABLEGEN=$CLANG_TABLEGEN \
-DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra;" \
-DLLVM_LIBDIR_SUFFIX=64 \
-DLLVM_BINUTILS_INCDIR=/usr/include \
-DLLVM_HOST_TRIPLE="x86_64-generic-linux" \
-DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3
ninja  %{?_smp_mflags}
unset PKG_CONFIG_PATH
popd
popd

%install
export SOURCE_DATE_EPOCH=1689819078
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/llvm15
cp %{_builddir}/llvm-project-%{version}.src/bolt/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm15/af07f365643f841c69797e9059b66f0bd847f1cd || :
cp %{_builddir}/llvm-project-%{version}.src/clang-tools-extra/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm15/a1691103171dc1d21cfa85f1d4809a16b9f1367f || :
cp %{_builddir}/llvm-project-%{version}.src/clang/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm15/a1691103171dc1d21cfa85f1d4809a16b9f1367f || :
cp %{_builddir}/llvm-project-%{version}.src/clang/tools/clang-format-vs/ClangFormat/license.txt %{buildroot}/usr/share/package-licenses/llvm15/b5d4ab4d1191e592c03310adfbe90d99a46bf9d7 || :
cp %{_builddir}/llvm-project-%{version}.src/compiler-rt/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm15/f4359b9da55a3b9e4d9513eb79cacf125fb49e7b || :
cp %{_builddir}/llvm-project-%{version}.src/cross-project-tests/debuginfo-tests/dexter/LICENSE.txt %{buildroot}/usr/share/package-licenses/llvm15/af07f365643f841c69797e9059b66f0bd847f1cd || :
cp %{_builddir}/llvm-project-%{version}.src/flang/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm15/85c0f2884378413881b4d3e27fc24b220f71889b || :
cp %{_builddir}/llvm-project-%{version}.src/libc/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm15/a1691103171dc1d21cfa85f1d4809a16b9f1367f || :
cp %{_builddir}/llvm-project-%{version}.src/libclc/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm15/8737af83de0d40386dca9a4abe2b6faa83cb4750 || :
cp %{_builddir}/llvm-project-%{version}.src/libcxx/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm15/7b75a5471af8b3d49e60df0a5d72f95ea8214231 || :
cp %{_builddir}/llvm-project-%{version}.src/libcxxabi/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm15/11156021d878bfcbdf2563b4f65db32b4d9f92a3 || :
cp %{_builddir}/llvm-project-%{version}.src/libunwind/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm15/d79062af10a33188d4a74d976323845a2cf9023d || :
cp %{_builddir}/llvm-project-%{version}.src/lld/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm15/6b655b0685aa7ee33fa1e02103b3bf22ed06e099 || :
cp %{_builddir}/llvm-project-%{version}.src/lldb/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm15/8af372ad1edbed2cfaf0e79d25f7136ec6e55b47 || :
cp %{_builddir}/llvm-project-%{version}.src/lldb/third_party/Python/module/pexpect-4.6/LICENSE %{buildroot}/usr/share/package-licenses/llvm15/5a99e7077ee89ba92fb3f584855e8970096cd5dc || :
cp %{_builddir}/llvm-project-%{version}.src/lldb/third_party/Python/module/ptyprocess-0.6.0/LICENSE %{buildroot}/usr/share/package-licenses/llvm15/db1f866b29c6a191752c7c5924b7572cdbc47c34 || :
cp %{_builddir}/llvm-project-%{version}.src/lldb/third_party/Python/module/six/LICENSE %{buildroot}/usr/share/package-licenses/llvm15/f226af67862c0c7a0e921e24672a3a1375691e3e || :
cp %{_builddir}/llvm-project-%{version}.src/llvm/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm15/af07f365643f841c69797e9059b66f0bd847f1cd || :
cp %{_builddir}/llvm-project-%{version}.src/llvm/include/llvm/Support/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm15/5feeec1755c1a12a9ade79c0db7ce0dd05baf119 || :
cp %{_builddir}/llvm-project-%{version}.src/llvm/lib/Support/BLAKE3/LICENSE %{buildroot}/usr/share/package-licenses/llvm15/bfc2b026231b7aca6db90de3471e76dbb94e9c24 || :
cp %{_builddir}/llvm-project-%{version}.src/llvm/test/YAMLParser/LICENSE.txt %{buildroot}/usr/share/package-licenses/llvm15/c01c212bdf3925189f673e2081b44094023860ea || :
cp %{_builddir}/llvm-project-%{version}.src/llvm/utils/lit/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm15/af07f365643f841c69797e9059b66f0bd847f1cd || :
cp %{_builddir}/llvm-project-%{version}.src/llvm/utils/unittest/googlemock/LICENSE.txt %{buildroot}/usr/share/package-licenses/llvm15/5a2314153eadadc69258a9429104cd11804ea304 || :
cp %{_builddir}/llvm-project-%{version}.src/llvm/utils/unittest/googletest/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm15/5a2314153eadadc69258a9429104cd11804ea304 || :
cp %{_builddir}/llvm-project-%{version}.src/mlir/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm15/85c0f2884378413881b4d3e27fc24b220f71889b || :
cp %{_builddir}/llvm-project-%{version}.src/openmp/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm15/e3cccabb67bd491a643d32a7d2b65b49836e626d || :
cp %{_builddir}/llvm-project-%{version}.src/openmp/runtime/src/thirdparty/ittnotify/LICENSE.txt %{buildroot}/usr/share/package-licenses/llvm15/59a8ba331dede4d94bd654ac645e8d27463662f4 || :
cp %{_builddir}/llvm-project-%{version}.src/polly/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm15/8d3b142938f83e7045951089b52676a5605eee37 || :
cp %{_builddir}/llvm-project-%{version}.src/polly/lib/External/isl/LICENSE %{buildroot}/usr/share/package-licenses/llvm15/45c2429b5881295597e96c81fc50f7b8a42e769f || :
cp %{_builddir}/llvm-project-%{version}.src/polly/lib/External/isl/imath/LICENSE %{buildroot}/usr/share/package-licenses/llvm15/385649e7c18da3a07cfbd6679eebd0bca1c698c9 || :
cp %{_builddir}/llvm-project-%{version}.src/polly/tools/GPURuntime/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm15/ce27417c74ca5ad6d0b5c96ede8ff82e4d87900f || :
cp %{_builddir}/llvm-project-%{version}.src/pstl/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm15/72c865be698cefc46549ed61e279f98432364fca || :
cp %{_builddir}/llvm-project-%{version}.src/third-party/benchmark/LICENSE %{buildroot}/usr/share/package-licenses/llvm15/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
pushd llvm
pushd clr-build32
%ninja_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
if [ -d %{buildroot}/usr/share/pkgconfig ]
then
pushd %{buildroot}/usr/share/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
pushd clr-build
%ninja_install
popd
popd
## Remove excluded files
rm -f %{buildroot}*/usr/lib64/libgomp.so
rm -f %{buildroot}*/usr/lib64/TestPlugin.so
rm -f %{buildroot}*/usr/lib64/cmake/llvm/LLVMStaticExports.cmake
rm -f %{buildroot}*/usr/lib64/cmake/llvm/LLVMStaticExports-relwithdebinfo.cmake
rm -f %{buildroot}*/usr/lib64/pkgconfig/LLVMSPIRVLib.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/SPIRV-Headers.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/'32*.pc'
rm -f %{buildroot}*/usr/lib/python3.11/site-packages/six.py
rm -f %{buildroot}*/usr/lib64/libclang.so.13
rm -f %{buildroot}*/usr/lib32/libclang.so.13
rm -f %{buildroot}*/usr/lib64/clang/14.0.4/lib/linux/*-i386.so
## install_append content
# Rename the Gold plugin elsewhere, as we're erasing *.so below
mv %{buildroot}/usr/lib64/LLVMgold.so %{buildroot}/usr/lib64/LLVMgold.so.save

# Remove files that should come from the main llvm package
rm -rf %{buildroot}/usr/include
rm -fr %{buildroot}/usr/lib/libear
rm -fr %{buildroot}/usr/lib/libscanbuild
rm -fr %{buildroot}/usr/lib/python3.11
rm -rf %{buildroot}/usr/lib64/*.a
rm -rf %{buildroot}/usr/lib64/*.so
rm -rf %{buildroot}/usr/lib64/cmake
rm -rf %{buildroot}/usr/lib64/pkgconfig
rm -rf %{buildroot}/usr/libexec

mv %{buildroot}/usr/share/package-licenses %{buildroot}/usr/
rm -rf %{buildroot}/usr/share/*
mv %{buildroot}/usr/package-licenses %{buildroot}/usr/share

# Rename the tools to have a versioned suffix and symlink back
pushd %{buildroot}/usr
FULL_VERSION=%{version}
VERSION=${FULL_VERSION%%%%.*}
mkdir -p lib64/clang/$FULL_VERSION/bin
mv bin/* lib64/clang/$FULL_VERSION/bin
for f in lib64/clang/$FULL_VERSION/bin/*; do
case "$f" in
*-$VERSION)
# Already versioned, leave it alone
continue
;;
esac
ln -s ../$f bin/${f##*/}-$VERSION
done

# libclang-cpp auto-relocates, so create a symlink so it finds its files
ln -s ../.. lib64/clang/$FULL_VERSION/lib64

# Put the LLVM gold plugin back, under the versioned name
mv lib64/LLVMgold.so.save lib64/LLVMgold-$VERSION.so

mkdir -p lib/bfd-plugins
ln -s ../../lib64/LLVMgold-$VERSION.so lib/bfd-plugins
popd
## install_append end

%files
%defattr(-,root,root,-)
/usr/lib64/clang/15.0.7/bin/analyze-build
/usr/lib64/clang/15.0.7/bin/bugpoint
/usr/lib64/clang/15.0.7/bin/c-index-test
/usr/lib64/clang/15.0.7/bin/clang
/usr/lib64/clang/15.0.7/bin/clang++
/usr/lib64/clang/15.0.7/bin/clang-15
/usr/lib64/clang/15.0.7/bin/clang-apply-replacements
/usr/lib64/clang/15.0.7/bin/clang-change-namespace
/usr/lib64/clang/15.0.7/bin/clang-check
/usr/lib64/clang/15.0.7/bin/clang-cl
/usr/lib64/clang/15.0.7/bin/clang-cpp
/usr/lib64/clang/15.0.7/bin/clang-doc
/usr/lib64/clang/15.0.7/bin/clang-extdef-mapping
/usr/lib64/clang/15.0.7/bin/clang-format
/usr/lib64/clang/15.0.7/bin/clang-include-fixer
/usr/lib64/clang/15.0.7/bin/clang-linker-wrapper
/usr/lib64/clang/15.0.7/bin/clang-move
/usr/lib64/clang/15.0.7/bin/clang-nvlink-wrapper
/usr/lib64/clang/15.0.7/bin/clang-offload-bundler
/usr/lib64/clang/15.0.7/bin/clang-offload-packager
/usr/lib64/clang/15.0.7/bin/clang-offload-wrapper
/usr/lib64/clang/15.0.7/bin/clang-pseudo
/usr/lib64/clang/15.0.7/bin/clang-query
/usr/lib64/clang/15.0.7/bin/clang-refactor
/usr/lib64/clang/15.0.7/bin/clang-rename
/usr/lib64/clang/15.0.7/bin/clang-reorder-fields
/usr/lib64/clang/15.0.7/bin/clang-repl
/usr/lib64/clang/15.0.7/bin/clang-scan-deps
/usr/lib64/clang/15.0.7/bin/clang-tidy
/usr/lib64/clang/15.0.7/bin/clangd
/usr/lib64/clang/15.0.7/bin/diagtool
/usr/lib64/clang/15.0.7/bin/dsymutil
/usr/lib64/clang/15.0.7/bin/find-all-symbols
/usr/lib64/clang/15.0.7/bin/git-clang-format
/usr/lib64/clang/15.0.7/bin/hmaptool
/usr/lib64/clang/15.0.7/bin/intercept-build
/usr/lib64/clang/15.0.7/bin/llc
/usr/lib64/clang/15.0.7/bin/lli
/usr/lib64/clang/15.0.7/bin/llvm-addr2line
/usr/lib64/clang/15.0.7/bin/llvm-ar
/usr/lib64/clang/15.0.7/bin/llvm-as
/usr/lib64/clang/15.0.7/bin/llvm-bcanalyzer
/usr/lib64/clang/15.0.7/bin/llvm-bitcode-strip
/usr/lib64/clang/15.0.7/bin/llvm-c-test
/usr/lib64/clang/15.0.7/bin/llvm-cat
/usr/lib64/clang/15.0.7/bin/llvm-cfi-verify
/usr/lib64/clang/15.0.7/bin/llvm-config
/usr/lib64/clang/15.0.7/bin/llvm-cov
/usr/lib64/clang/15.0.7/bin/llvm-cvtres
/usr/lib64/clang/15.0.7/bin/llvm-cxxdump
/usr/lib64/clang/15.0.7/bin/llvm-cxxfilt
/usr/lib64/clang/15.0.7/bin/llvm-cxxmap
/usr/lib64/clang/15.0.7/bin/llvm-debuginfod
/usr/lib64/clang/15.0.7/bin/llvm-debuginfod-find
/usr/lib64/clang/15.0.7/bin/llvm-diff
/usr/lib64/clang/15.0.7/bin/llvm-dis
/usr/lib64/clang/15.0.7/bin/llvm-dlltool
/usr/lib64/clang/15.0.7/bin/llvm-dwarfdump
/usr/lib64/clang/15.0.7/bin/llvm-dwarfutil
/usr/lib64/clang/15.0.7/bin/llvm-dwp
/usr/lib64/clang/15.0.7/bin/llvm-exegesis
/usr/lib64/clang/15.0.7/bin/llvm-extract
/usr/lib64/clang/15.0.7/bin/llvm-gsymutil
/usr/lib64/clang/15.0.7/bin/llvm-ifs
/usr/lib64/clang/15.0.7/bin/llvm-install-name-tool
/usr/lib64/clang/15.0.7/bin/llvm-jitlink
/usr/lib64/clang/15.0.7/bin/llvm-lib
/usr/lib64/clang/15.0.7/bin/llvm-libtool-darwin
/usr/lib64/clang/15.0.7/bin/llvm-link
/usr/lib64/clang/15.0.7/bin/llvm-lipo
/usr/lib64/clang/15.0.7/bin/llvm-lto
/usr/lib64/clang/15.0.7/bin/llvm-lto2
/usr/lib64/clang/15.0.7/bin/llvm-mc
/usr/lib64/clang/15.0.7/bin/llvm-mca
/usr/lib64/clang/15.0.7/bin/llvm-ml
/usr/lib64/clang/15.0.7/bin/llvm-modextract
/usr/lib64/clang/15.0.7/bin/llvm-mt
/usr/lib64/clang/15.0.7/bin/llvm-nm
/usr/lib64/clang/15.0.7/bin/llvm-objcopy
/usr/lib64/clang/15.0.7/bin/llvm-objdump
/usr/lib64/clang/15.0.7/bin/llvm-opt-report
/usr/lib64/clang/15.0.7/bin/llvm-otool
/usr/lib64/clang/15.0.7/bin/llvm-pdbutil
/usr/lib64/clang/15.0.7/bin/llvm-profdata
/usr/lib64/clang/15.0.7/bin/llvm-profgen
/usr/lib64/clang/15.0.7/bin/llvm-ranlib
/usr/lib64/clang/15.0.7/bin/llvm-rc
/usr/lib64/clang/15.0.7/bin/llvm-readelf
/usr/lib64/clang/15.0.7/bin/llvm-readobj
/usr/lib64/clang/15.0.7/bin/llvm-reduce
/usr/lib64/clang/15.0.7/bin/llvm-remark-size-diff
/usr/lib64/clang/15.0.7/bin/llvm-rtdyld
/usr/lib64/clang/15.0.7/bin/llvm-sim
/usr/lib64/clang/15.0.7/bin/llvm-size
/usr/lib64/clang/15.0.7/bin/llvm-split
/usr/lib64/clang/15.0.7/bin/llvm-stress
/usr/lib64/clang/15.0.7/bin/llvm-strings
/usr/lib64/clang/15.0.7/bin/llvm-strip
/usr/lib64/clang/15.0.7/bin/llvm-symbolizer
/usr/lib64/clang/15.0.7/bin/llvm-tapi-diff
/usr/lib64/clang/15.0.7/bin/llvm-tblgen
/usr/lib64/clang/15.0.7/bin/llvm-tli-checker
/usr/lib64/clang/15.0.7/bin/llvm-undname
/usr/lib64/clang/15.0.7/bin/llvm-windres
/usr/lib64/clang/15.0.7/bin/llvm-xray
/usr/lib64/clang/15.0.7/bin/modularize
/usr/lib64/clang/15.0.7/bin/opt
/usr/lib64/clang/15.0.7/bin/pp-trace
/usr/lib64/clang/15.0.7/bin/run-clang-tidy
/usr/lib64/clang/15.0.7/bin/sancov
/usr/lib64/clang/15.0.7/bin/sanstats
/usr/lib64/clang/15.0.7/bin/scan-build
/usr/lib64/clang/15.0.7/bin/scan-build-py
/usr/lib64/clang/15.0.7/bin/scan-view
/usr/lib64/clang/15.0.7/bin/split-file
/usr/lib64/clang/15.0.7/bin/verify-uselistorder
/usr/lib64/clang/15.0.7/include/cuda_wrappers/algorithm
/usr/lib64/clang/15.0.7/include/cuda_wrappers/complex
/usr/lib64/clang/15.0.7/include/cuda_wrappers/new
/usr/lib64/clang/15.0.7/include/module.modulemap
/usr/lib64/clang/15.0.7/include/openmp_wrappers/cmath
/usr/lib64/clang/15.0.7/include/openmp_wrappers/complex
/usr/lib64/clang/15.0.7/include/openmp_wrappers/new
/usr/lib64/clang/15.0.7/lib64

%files bin
%defattr(-,root,root,-)
/usr/bin/analyze-build-15
/usr/bin/bugpoint-15
/usr/bin/c-index-test-15
/usr/bin/clang++-15
/usr/bin/clang-15
/usr/bin/clang-apply-replacements-15
/usr/bin/clang-change-namespace-15
/usr/bin/clang-check-15
/usr/bin/clang-cl-15
/usr/bin/clang-cpp-15
/usr/bin/clang-doc-15
/usr/bin/clang-extdef-mapping-15
/usr/bin/clang-format-15
/usr/bin/clang-include-fixer-15
/usr/bin/clang-linker-wrapper-15
/usr/bin/clang-move-15
/usr/bin/clang-nvlink-wrapper-15
/usr/bin/clang-offload-bundler-15
/usr/bin/clang-offload-packager-15
/usr/bin/clang-offload-wrapper-15
/usr/bin/clang-pseudo-15
/usr/bin/clang-query-15
/usr/bin/clang-refactor-15
/usr/bin/clang-rename-15
/usr/bin/clang-reorder-fields-15
/usr/bin/clang-repl-15
/usr/bin/clang-scan-deps-15
/usr/bin/clang-tidy-15
/usr/bin/clangd-15
/usr/bin/diagtool-15
/usr/bin/dsymutil-15
/usr/bin/find-all-symbols-15
/usr/bin/git-clang-format-15
/usr/bin/hmaptool-15
/usr/bin/intercept-build-15
/usr/bin/llc-15
/usr/bin/lli-15
/usr/bin/llvm-addr2line-15
/usr/bin/llvm-ar-15
/usr/bin/llvm-as-15
/usr/bin/llvm-bcanalyzer-15
/usr/bin/llvm-bitcode-strip-15
/usr/bin/llvm-c-test-15
/usr/bin/llvm-cat-15
/usr/bin/llvm-cfi-verify-15
/usr/bin/llvm-config-15
/usr/bin/llvm-cov-15
/usr/bin/llvm-cvtres-15
/usr/bin/llvm-cxxdump-15
/usr/bin/llvm-cxxfilt-15
/usr/bin/llvm-cxxmap-15
/usr/bin/llvm-debuginfod-15
/usr/bin/llvm-debuginfod-find-15
/usr/bin/llvm-diff-15
/usr/bin/llvm-dis-15
/usr/bin/llvm-dlltool-15
/usr/bin/llvm-dwarfdump-15
/usr/bin/llvm-dwarfutil-15
/usr/bin/llvm-dwp-15
/usr/bin/llvm-exegesis-15
/usr/bin/llvm-extract-15
/usr/bin/llvm-gsymutil-15
/usr/bin/llvm-ifs-15
/usr/bin/llvm-install-name-tool-15
/usr/bin/llvm-jitlink-15
/usr/bin/llvm-lib-15
/usr/bin/llvm-libtool-darwin-15
/usr/bin/llvm-link-15
/usr/bin/llvm-lipo-15
/usr/bin/llvm-lto-15
/usr/bin/llvm-lto2-15
/usr/bin/llvm-mc-15
/usr/bin/llvm-mca-15
/usr/bin/llvm-ml-15
/usr/bin/llvm-modextract-15
/usr/bin/llvm-mt-15
/usr/bin/llvm-nm-15
/usr/bin/llvm-objcopy-15
/usr/bin/llvm-objdump-15
/usr/bin/llvm-opt-report-15
/usr/bin/llvm-otool-15
/usr/bin/llvm-pdbutil-15
/usr/bin/llvm-profdata-15
/usr/bin/llvm-profgen-15
/usr/bin/llvm-ranlib-15
/usr/bin/llvm-rc-15
/usr/bin/llvm-readelf-15
/usr/bin/llvm-readobj-15
/usr/bin/llvm-reduce-15
/usr/bin/llvm-remark-size-diff-15
/usr/bin/llvm-rtdyld-15
/usr/bin/llvm-sim-15
/usr/bin/llvm-size-15
/usr/bin/llvm-split-15
/usr/bin/llvm-stress-15
/usr/bin/llvm-strings-15
/usr/bin/llvm-strip-15
/usr/bin/llvm-symbolizer-15
/usr/bin/llvm-tapi-diff-15
/usr/bin/llvm-tblgen-15
/usr/bin/llvm-tli-checker-15
/usr/bin/llvm-undname-15
/usr/bin/llvm-windres-15
/usr/bin/llvm-xray-15
/usr/bin/modularize-15
/usr/bin/opt-15
/usr/bin/pp-trace-15
/usr/bin/run-clang-tidy-15
/usr/bin/sancov-15
/usr/bin/sanstats-15
/usr/bin/scan-build-15
/usr/bin/scan-build-py-15
/usr/bin/scan-view-15
/usr/bin/split-file-15
/usr/bin/verify-uselistorder-15

%files dev
%defattr(-,root,root,-)
/usr/lib64/LLVMgold-15.so
/usr/lib64/clang/15.0.7/include/__clang_cuda_builtin_vars.h
/usr/lib64/clang/15.0.7/include/__clang_cuda_cmath.h
/usr/lib64/clang/15.0.7/include/__clang_cuda_complex_builtins.h
/usr/lib64/clang/15.0.7/include/__clang_cuda_device_functions.h
/usr/lib64/clang/15.0.7/include/__clang_cuda_intrinsics.h
/usr/lib64/clang/15.0.7/include/__clang_cuda_libdevice_declares.h
/usr/lib64/clang/15.0.7/include/__clang_cuda_math.h
/usr/lib64/clang/15.0.7/include/__clang_cuda_math_forward_declares.h
/usr/lib64/clang/15.0.7/include/__clang_cuda_runtime_wrapper.h
/usr/lib64/clang/15.0.7/include/__clang_cuda_texture_intrinsics.h
/usr/lib64/clang/15.0.7/include/__clang_hip_cmath.h
/usr/lib64/clang/15.0.7/include/__clang_hip_libdevice_declares.h
/usr/lib64/clang/15.0.7/include/__clang_hip_math.h
/usr/lib64/clang/15.0.7/include/__clang_hip_runtime_wrapper.h
/usr/lib64/clang/15.0.7/include/__stddef_max_align_t.h
/usr/lib64/clang/15.0.7/include/__wmmintrin_aes.h
/usr/lib64/clang/15.0.7/include/__wmmintrin_pclmul.h
/usr/lib64/clang/15.0.7/include/adxintrin.h
/usr/lib64/clang/15.0.7/include/altivec.h
/usr/lib64/clang/15.0.7/include/ammintrin.h
/usr/lib64/clang/15.0.7/include/amxintrin.h
/usr/lib64/clang/15.0.7/include/arm64intr.h
/usr/lib64/clang/15.0.7/include/arm_acle.h
/usr/lib64/clang/15.0.7/include/arm_bf16.h
/usr/lib64/clang/15.0.7/include/arm_cde.h
/usr/lib64/clang/15.0.7/include/arm_cmse.h
/usr/lib64/clang/15.0.7/include/arm_fp16.h
/usr/lib64/clang/15.0.7/include/arm_mve.h
/usr/lib64/clang/15.0.7/include/arm_neon.h
/usr/lib64/clang/15.0.7/include/arm_sve.h
/usr/lib64/clang/15.0.7/include/armintr.h
/usr/lib64/clang/15.0.7/include/avx2intrin.h
/usr/lib64/clang/15.0.7/include/avx512bf16intrin.h
/usr/lib64/clang/15.0.7/include/avx512bitalgintrin.h
/usr/lib64/clang/15.0.7/include/avx512bwintrin.h
/usr/lib64/clang/15.0.7/include/avx512cdintrin.h
/usr/lib64/clang/15.0.7/include/avx512dqintrin.h
/usr/lib64/clang/15.0.7/include/avx512erintrin.h
/usr/lib64/clang/15.0.7/include/avx512fintrin.h
/usr/lib64/clang/15.0.7/include/avx512fp16intrin.h
/usr/lib64/clang/15.0.7/include/avx512ifmaintrin.h
/usr/lib64/clang/15.0.7/include/avx512ifmavlintrin.h
/usr/lib64/clang/15.0.7/include/avx512pfintrin.h
/usr/lib64/clang/15.0.7/include/avx512vbmi2intrin.h
/usr/lib64/clang/15.0.7/include/avx512vbmiintrin.h
/usr/lib64/clang/15.0.7/include/avx512vbmivlintrin.h
/usr/lib64/clang/15.0.7/include/avx512vlbf16intrin.h
/usr/lib64/clang/15.0.7/include/avx512vlbitalgintrin.h
/usr/lib64/clang/15.0.7/include/avx512vlbwintrin.h
/usr/lib64/clang/15.0.7/include/avx512vlcdintrin.h
/usr/lib64/clang/15.0.7/include/avx512vldqintrin.h
/usr/lib64/clang/15.0.7/include/avx512vlfp16intrin.h
/usr/lib64/clang/15.0.7/include/avx512vlintrin.h
/usr/lib64/clang/15.0.7/include/avx512vlvbmi2intrin.h
/usr/lib64/clang/15.0.7/include/avx512vlvnniintrin.h
/usr/lib64/clang/15.0.7/include/avx512vlvp2intersectintrin.h
/usr/lib64/clang/15.0.7/include/avx512vnniintrin.h
/usr/lib64/clang/15.0.7/include/avx512vp2intersectintrin.h
/usr/lib64/clang/15.0.7/include/avx512vpopcntdqintrin.h
/usr/lib64/clang/15.0.7/include/avx512vpopcntdqvlintrin.h
/usr/lib64/clang/15.0.7/include/avxintrin.h
/usr/lib64/clang/15.0.7/include/avxvnniintrin.h
/usr/lib64/clang/15.0.7/include/bmi2intrin.h
/usr/lib64/clang/15.0.7/include/bmiintrin.h
/usr/lib64/clang/15.0.7/include/builtins.h
/usr/lib64/clang/15.0.7/include/cet.h
/usr/lib64/clang/15.0.7/include/cetintrin.h
/usr/lib64/clang/15.0.7/include/cldemoteintrin.h
/usr/lib64/clang/15.0.7/include/clflushoptintrin.h
/usr/lib64/clang/15.0.7/include/clwbintrin.h
/usr/lib64/clang/15.0.7/include/clzerointrin.h
/usr/lib64/clang/15.0.7/include/cpuid.h
/usr/lib64/clang/15.0.7/include/crc32intrin.h
/usr/lib64/clang/15.0.7/include/emmintrin.h
/usr/lib64/clang/15.0.7/include/enqcmdintrin.h
/usr/lib64/clang/15.0.7/include/f16cintrin.h
/usr/lib64/clang/15.0.7/include/float.h
/usr/lib64/clang/15.0.7/include/fma4intrin.h
/usr/lib64/clang/15.0.7/include/fmaintrin.h
/usr/lib64/clang/15.0.7/include/fxsrintrin.h
/usr/lib64/clang/15.0.7/include/gfniintrin.h
/usr/lib64/clang/15.0.7/include/hexagon_circ_brev_intrinsics.h
/usr/lib64/clang/15.0.7/include/hexagon_protos.h
/usr/lib64/clang/15.0.7/include/hexagon_types.h
/usr/lib64/clang/15.0.7/include/hlsl.h
/usr/lib64/clang/15.0.7/include/hlsl_basic_types.h
/usr/lib64/clang/15.0.7/include/hlsl_intrinsics.h
/usr/lib64/clang/15.0.7/include/hresetintrin.h
/usr/lib64/clang/15.0.7/include/htmintrin.h
/usr/lib64/clang/15.0.7/include/htmxlintrin.h
/usr/lib64/clang/15.0.7/include/hvx_hexagon_protos.h
/usr/lib64/clang/15.0.7/include/ia32intrin.h
/usr/lib64/clang/15.0.7/include/immintrin.h
/usr/lib64/clang/15.0.7/include/intrin.h
/usr/lib64/clang/15.0.7/include/inttypes.h
/usr/lib64/clang/15.0.7/include/invpcidintrin.h
/usr/lib64/clang/15.0.7/include/iso646.h
/usr/lib64/clang/15.0.7/include/keylockerintrin.h
/usr/lib64/clang/15.0.7/include/limits.h
/usr/lib64/clang/15.0.7/include/lwpintrin.h
/usr/lib64/clang/15.0.7/include/lzcntintrin.h
/usr/lib64/clang/15.0.7/include/mm3dnow.h
/usr/lib64/clang/15.0.7/include/mm_malloc.h
/usr/lib64/clang/15.0.7/include/mmintrin.h
/usr/lib64/clang/15.0.7/include/movdirintrin.h
/usr/lib64/clang/15.0.7/include/msa.h
/usr/lib64/clang/15.0.7/include/mwaitxintrin.h
/usr/lib64/clang/15.0.7/include/nmmintrin.h
/usr/lib64/clang/15.0.7/include/opencl-c-base.h
/usr/lib64/clang/15.0.7/include/opencl-c.h
/usr/lib64/clang/15.0.7/include/openmp_wrappers/__clang_openmp_device_functions.h
/usr/lib64/clang/15.0.7/include/openmp_wrappers/complex.h
/usr/lib64/clang/15.0.7/include/openmp_wrappers/complex_cmath.h
/usr/lib64/clang/15.0.7/include/openmp_wrappers/math.h
/usr/lib64/clang/15.0.7/include/pconfigintrin.h
/usr/lib64/clang/15.0.7/include/pkuintrin.h
/usr/lib64/clang/15.0.7/include/pmmintrin.h
/usr/lib64/clang/15.0.7/include/popcntintrin.h
/usr/lib64/clang/15.0.7/include/ppc_wrappers/bmi2intrin.h
/usr/lib64/clang/15.0.7/include/ppc_wrappers/bmiintrin.h
/usr/lib64/clang/15.0.7/include/ppc_wrappers/emmintrin.h
/usr/lib64/clang/15.0.7/include/ppc_wrappers/immintrin.h
/usr/lib64/clang/15.0.7/include/ppc_wrappers/mm_malloc.h
/usr/lib64/clang/15.0.7/include/ppc_wrappers/mmintrin.h
/usr/lib64/clang/15.0.7/include/ppc_wrappers/pmmintrin.h
/usr/lib64/clang/15.0.7/include/ppc_wrappers/smmintrin.h
/usr/lib64/clang/15.0.7/include/ppc_wrappers/tmmintrin.h
/usr/lib64/clang/15.0.7/include/ppc_wrappers/x86gprintrin.h
/usr/lib64/clang/15.0.7/include/ppc_wrappers/x86intrin.h
/usr/lib64/clang/15.0.7/include/ppc_wrappers/xmmintrin.h
/usr/lib64/clang/15.0.7/include/prfchwintrin.h
/usr/lib64/clang/15.0.7/include/ptwriteintrin.h
/usr/lib64/clang/15.0.7/include/rdpruintrin.h
/usr/lib64/clang/15.0.7/include/rdseedintrin.h
/usr/lib64/clang/15.0.7/include/riscv_vector.h
/usr/lib64/clang/15.0.7/include/rtmintrin.h
/usr/lib64/clang/15.0.7/include/s390intrin.h
/usr/lib64/clang/15.0.7/include/serializeintrin.h
/usr/lib64/clang/15.0.7/include/sgxintrin.h
/usr/lib64/clang/15.0.7/include/shaintrin.h
/usr/lib64/clang/15.0.7/include/smmintrin.h
/usr/lib64/clang/15.0.7/include/stdalign.h
/usr/lib64/clang/15.0.7/include/stdarg.h
/usr/lib64/clang/15.0.7/include/stdatomic.h
/usr/lib64/clang/15.0.7/include/stdbool.h
/usr/lib64/clang/15.0.7/include/stddef.h
/usr/lib64/clang/15.0.7/include/stdint.h
/usr/lib64/clang/15.0.7/include/stdnoreturn.h
/usr/lib64/clang/15.0.7/include/tbmintrin.h
/usr/lib64/clang/15.0.7/include/tgmath.h
/usr/lib64/clang/15.0.7/include/tmmintrin.h
/usr/lib64/clang/15.0.7/include/tsxldtrkintrin.h
/usr/lib64/clang/15.0.7/include/uintrintrin.h
/usr/lib64/clang/15.0.7/include/unwind.h
/usr/lib64/clang/15.0.7/include/vadefs.h
/usr/lib64/clang/15.0.7/include/vaesintrin.h
/usr/lib64/clang/15.0.7/include/varargs.h
/usr/lib64/clang/15.0.7/include/vecintrin.h
/usr/lib64/clang/15.0.7/include/velintrin.h
/usr/lib64/clang/15.0.7/include/velintrin_approx.h
/usr/lib64/clang/15.0.7/include/velintrin_gen.h
/usr/lib64/clang/15.0.7/include/vpclmulqdqintrin.h
/usr/lib64/clang/15.0.7/include/waitpkgintrin.h
/usr/lib64/clang/15.0.7/include/wasm_simd128.h
/usr/lib64/clang/15.0.7/include/wbnoinvdintrin.h
/usr/lib64/clang/15.0.7/include/wmmintrin.h
/usr/lib64/clang/15.0.7/include/x86gprintrin.h
/usr/lib64/clang/15.0.7/include/x86intrin.h
/usr/lib64/clang/15.0.7/include/xmmintrin.h
/usr/lib64/clang/15.0.7/include/xopintrin.h
/usr/lib64/clang/15.0.7/include/xsavecintrin.h
/usr/lib64/clang/15.0.7/include/xsaveintrin.h
/usr/lib64/clang/15.0.7/include/xsaveoptintrin.h
/usr/lib64/clang/15.0.7/include/xsavesintrin.h
/usr/lib64/clang/15.0.7/include/xtestintrin.h

%files extras-libclang
%defattr(-,root,root,-)
/usr/lib64/libclang.so.15.0.7

%files extras-libclang-cpp
%defattr(-,root,root,-)
/usr/lib64/libclang-cpp.so.15

%files extras-libllvm
%defattr(-,root,root,-)
/usr/lib64/libLLVM.so.15

%files lib
%defattr(-,root,root,-)
/usr/lib/bfd-plugins/LLVMgold-15.so
/usr/lib64/libLTO.so.15
/usr/lib64/libRemarks.so.15
/usr/lib64/libclang.so.15

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/llvm15/11156021d878bfcbdf2563b4f65db32b4d9f92a3
/usr/share/package-licenses/llvm15/2b8b815229aa8a61e483fb4ba0588b8b6c491890
/usr/share/package-licenses/llvm15/385649e7c18da3a07cfbd6679eebd0bca1c698c9
/usr/share/package-licenses/llvm15/45c2429b5881295597e96c81fc50f7b8a42e769f
/usr/share/package-licenses/llvm15/59a8ba331dede4d94bd654ac645e8d27463662f4
/usr/share/package-licenses/llvm15/5a2314153eadadc69258a9429104cd11804ea304
/usr/share/package-licenses/llvm15/5a99e7077ee89ba92fb3f584855e8970096cd5dc
/usr/share/package-licenses/llvm15/5feeec1755c1a12a9ade79c0db7ce0dd05baf119
/usr/share/package-licenses/llvm15/6b655b0685aa7ee33fa1e02103b3bf22ed06e099
/usr/share/package-licenses/llvm15/72c865be698cefc46549ed61e279f98432364fca
/usr/share/package-licenses/llvm15/7b75a5471af8b3d49e60df0a5d72f95ea8214231
/usr/share/package-licenses/llvm15/85c0f2884378413881b4d3e27fc24b220f71889b
/usr/share/package-licenses/llvm15/8737af83de0d40386dca9a4abe2b6faa83cb4750
/usr/share/package-licenses/llvm15/8af372ad1edbed2cfaf0e79d25f7136ec6e55b47
/usr/share/package-licenses/llvm15/8d3b142938f83e7045951089b52676a5605eee37
/usr/share/package-licenses/llvm15/a1691103171dc1d21cfa85f1d4809a16b9f1367f
/usr/share/package-licenses/llvm15/af07f365643f841c69797e9059b66f0bd847f1cd
/usr/share/package-licenses/llvm15/b5d4ab4d1191e592c03310adfbe90d99a46bf9d7
/usr/share/package-licenses/llvm15/bfc2b026231b7aca6db90de3471e76dbb94e9c24
/usr/share/package-licenses/llvm15/c01c212bdf3925189f673e2081b44094023860ea
/usr/share/package-licenses/llvm15/ce27417c74ca5ad6d0b5c96ede8ff82e4d87900f
/usr/share/package-licenses/llvm15/d79062af10a33188d4a74d976323845a2cf9023d
/usr/share/package-licenses/llvm15/db1f866b29c6a191752c7c5924b7572cdbc47c34
/usr/share/package-licenses/llvm15/e3cccabb67bd491a643d32a7d2b65b49836e626d
/usr/share/package-licenses/llvm15/f226af67862c0c7a0e921e24672a3a1375691e3e
/usr/share/package-licenses/llvm15/f4359b9da55a3b9e4d9513eb79cacf125fb49e7b
